name: Continuous Integration

on: [push]                      # Will make the workflow run every time you push to any branch



jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest      # Sets the build environment a machine with the latest Ubuntu installed
    steps:
    - uses: actions/checkout@v2 # Adds a step to checkout the repository code
    - uses: actions/setup-dotnet@v1
    - name: Build
      run: dotnet build
    - name: Test 
      working-directory: ./DotnetTemplate.Web
      run: dotnet test 
    - name: BuildTypeScript
      working-directory: ./DotnetTemplate.Web
      run: npm install
    - name: Linter
      working-directory: ./DotnetTemplate.Web
      run: npm run lint
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Push to Docker Hub
      branches:
        only:
        - module-7
      uses: docker/build-push-action@v2
      with:
        file: Dockerfile.Hub
        push: true
        tags: aj1993/dotnettemplate:latest, aj1993/dotnettemplate:${{github.sha}}